apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: weather-service
  labels:
    app: core-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
        tier: backend
    spec:
      containers:
      - name: core-service
        image: scottweatherservice/core-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: MONGODB_URI
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: MONGODB_PASSWORD
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: weather-service-config
              key: REDIS_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: MICROSOFT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: MICROSOFT_CLIENT_ID
        - name: MICROSOFT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: weather-service-secrets
              key: MICROSOFT_CLIENT_SECRET
        envFrom:
        - configMapRef:
            name: weather-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: weather-service
  labels:
    app: core-service
spec:
  selector:
    app: core-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: core-service-hpa
  namespace: weather-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

