apiVersion: v1
kind: Namespace
metadata:
  name: weather-service
  labels:
    name: weather-service
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-service-config
  namespace: weather-service
data:
  # Service URLs
  CORE_SERVICE_URL: "http://core-service:8000"
  CALENDAR_SERVICE_URL: "http://calendar-service:8000"
  WEATHER_SERVICE_URL: "http://weather-service:8000"
  
  # Development Settings
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  
  # Redis Configuration
  REDIS_URL: "redis://redis-service:6379"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Cache Settings
  CACHE_ENABLED: "true"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  
  # CORS Settings
  CORS_ORIGINS: "https://scottweather.com,https://www.scottweather.com"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Content-Type,Authorization"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  
  # Health Check Settings
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "10"
  HEALTH_CHECK_RETRIES: "3"
  
  # Weather Service Configuration
  WEATHER_CACHE_TTL: "600"
  WEATHER_FORECAST_DAYS: "5"
  WEATHER_ALERT_THRESHOLD: "0.8"
  
  # Calendar Service Configuration
  CALENDAR_SYNC_INTERVAL: "300"
  
  # Recommendation Service Configuration
  RECOMMENDATION_CACHE_TTL: "3600"
  RECOMMENDATION_BATCH_SIZE: "10"
  RECOMMENDATION_CONFIDENCE_THRESHOLD: "0.7"
  
  # WebSocket Settings
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PING_INTERVAL: "25"
  WEBSOCKET_PING_TIMEOUT: "60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: weather-service
data:
  # Frontend Environment Variables
  REACT_APP_API_URL: "https://api.scottweather.com"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_DEBUG: "false"
  
  # WebSocket Configuration
  REACT_APP_WEBSOCKET_ENABLED: "true"
  REACT_APP_WEBSOCKET_URL: "wss://api.scottweather.com/ws"
  
  # Feature Flags
  REACT_APP_ENABLE_ANALYTICS: "true"
  REACT_APP_ENABLE_NOTIFICATIONS: "true"
  REACT_APP_ENABLE_OFFLINE_MODE: "false"

